@file:Suppress("UNUSED_PARAMETER")

package canon.visitor

import canon.api.IRenderable
import canon.api.IVisitor
import canon.model.*
import canon.model.Map

typealias KMap = kotlin.collections.Map<String, Any>

abstract class AbstractVisitor<R>(private val context: KMap) : IVisitor<List<R>> {

    override fun getContext() = context

    override fun visitRenderable(renderable: IRenderable?):List<R> {
        return when (renderable) {
            is Basket -> visitBasket(renderable)
            is Block -> visitBlock(renderable)
            is Bold -> visitBold(renderable)
            is Break -> visitBreak(renderable)
            is Button -> visitButton(renderable)
            is Calendar -> visitCalendar(renderable)
            is Camera -> visitCamera(renderable)
            is Carousel -> visitCarousel(renderable)
            is Checkbox -> visitCheckbox(renderable)
            is Choice -> visitChoice(renderable)
            is CodeReader -> visitCodeReader(renderable)
            is Col -> visitCol(renderable)
            is Container -> visitContainer(renderable)
            is Email -> visitEmail(renderable)
            is Foreach -> visitForeach(renderable)
            is Form -> visitForm(renderable)
            is Headline -> visitHeadline(renderable)
            is If -> visitIf(renderable)
            is Image -> visitImage(renderable)
            is Italic -> visitItalic(renderable)
            is Items -> visitItems(renderable)
            is Item -> visitItem(renderable)
            is Label -> visitLabel(renderable)
            is Link -> visitLink(renderable)
            is Map -> visitMap(renderable)
            is MultipleChoice -> visitMultipleChoice(renderable)
            is Overlay -> visitOverlay(renderable)
            is Overlays -> visitOverlays(renderable)
            is Phone -> visitPhone(renderable)
            is Reel -> visitReel(renderable)
            is ReelValue -> visitReelValue(renderable)
            is Row -> visitRow(renderable)
            is Selection -> visitSelection(renderable)
            is SingleChoice -> visitSingleChoice(renderable)
            is Slider -> visitSlider(renderable)
            is SlotMachine -> visitSlotMachine(renderable)
            is Spinner -> visitSpinner(renderable)
            is Submit -> visitSubmit(renderable)
            is Suggestion -> visitSuggestion(renderable)
            is Table -> visitTable(renderable)
            is Text -> visitText(renderable)
            is TextInput -> visitTextInput(renderable)
            is Textarea -> visitTextarea(renderable)
            is Transition -> visitTransition(renderable)
            is Trigger -> visitTrigger(renderable)
            is Upload -> visitUpload(renderable)
            is Video -> visitVideo(renderable)
            is NewText -> visitNewText(renderable)
            else -> throw IllegalArgumentException("renderable (${renderable?.getType()}) $renderable not implemented")
        }
    }

    open fun visitBasket(renderable: Basket) = listOf<R>()
    open fun visitBlock(renderable: Block) = listOf<R>()
    open fun visitBold(renderable: Bold) = listOf<R>()
    open fun visitBreak(renderable: Break) = listOf<R>()
    open fun visitButton(renderable: Button) = listOf<R>()
    open fun visitCalendar(renderable: Calendar) = listOf<R>()
    open fun visitCamera(renderable: Camera) = listOf<R>()
    open fun visitCarousel(renderable: Carousel) = listOf<R>()
    @Deprecated("will be removed in a future release", replaceWith = ReplaceWith("multipleChoice"))
    open fun visitCheckbox(renderable: Checkbox) = listOf<R>()
    open fun visitChoice(renderable: Choice) = listOf<R>()
    open fun visitCodeReader(renderable: CodeReader) = listOf<R>()
    open fun visitCol(renderable: Col) = listOf<R>()
    open fun visitContainer(renderable: Container) = listOf<R>()
    open fun visitEmail(renderable: Email) = listOf<R>()
    open fun visitForeach(renderable: Foreach) = listOf<R>()
    open fun visitForm(renderable: Form) = listOf<R>()
    open fun visitHeadline(renderable: Headline) = listOf<R>()
    open fun visitIf(renderable: If) = listOf<R>()
    open fun visitImage(renderable: Image) = listOf<R>()
    open fun visitItalic(renderable: Italic) = listOf<R>()
    open fun visitItems(renderable: Items) = listOf<R>()
    open fun visitItem(renderable: Item) = listOf<R>()
    open fun visitLabel(renderable: Label) = listOf<R>()
    open fun visitLink(renderable: Link) = listOf<R>()
    open fun visitMap(renderable: Map) = listOf<R>()
    open fun visitMultipleChoice(renderable: MultipleChoice) = listOf<R>()
    open fun visitOverlay(renderable: Overlay) = listOf<R>()
    open fun visitOverlays(renderable: Overlays) = listOf<R>()
    open fun visitPhone(renderable: Phone) = listOf<R>()
    open fun visitReel(renderable: Reel) = listOf<R>()
    open fun visitReelValue(renderable: ReelValue) = listOf<R>()
    open fun visitRow(renderable: Row) = listOf<R>()
    open fun visitSelection(renderable: Selection) = listOf<R>()
    open fun visitSingleChoice(renderable: SingleChoice) = listOf<R>()
    open fun visitSlider(renderable: Slider) = listOf<R>()
    open fun visitSlotMachine(renderable: SlotMachine) = listOf<R>()
    open fun visitSpinner(renderable: Spinner) = listOf<R>()
    open fun visitSubmit(renderable: Submit) = listOf<R>()
    open fun visitSuggestion(renderable: Suggestion) = listOf<R>()
    open fun visitTable(renderable: Table) = listOf<R>()
    open fun visitText(renderable: Text) = listOf<R>()
    open fun visitTextInput(renderable: TextInput) = listOf<R>()
    open fun visitTextarea(renderable: Textarea) = listOf<R>()
    open fun visitNewText(renderable: NewText) = listOf<R>()
    open fun visitTransition(renderable: Transition) = listOf<R>()
    open fun visitTrigger(renderable: Trigger) = listOf<R>()
    open fun visitUpload(renderable: Upload) = listOf<R>()
    open fun visitVideo(renderable: Video) = listOf<R>()
}
